// <auto-generated />
using System;
using JobJournal.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobJournal.Server.Migrations
{
    [DbContext(typeof(JobJournalContext))]
    partial class JobJournalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobJournal.Shared.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebsiteURI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad94a572-5104-4303-82f7-fac0a7d06897"),
                            City = "Muscatine",
                            CompanyName = "Schwabenlander.com",
                            EmailAddress = "sean@schwabenlander.com",
                            PhoneNumber = "(202) 794-0474",
                            State = "IA",
                            UserId = new Guid("9b27e7b5-1acf-42c8-919a-6394fd1ddfe8"),
                            WebsiteURI = "https://www.schwabenlander.com"
                        });
                });

            modelBuilder.Entity("JobJournal.Shared.CompanyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstContactDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MostRecentContactDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyContact");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e98b65b-c56d-470d-b509-148ac693a013"),
                            CompanyId = new Guid("ad94a572-5104-4303-82f7-fac0a7d06897"),
                            EmailAddress = "sean@schwabenlander.net",
                            FirstContactDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sean Schwabenlander",
                            PhoneNumber = "(612) 810-4212",
                            UserId = new Guid("9b27e7b5-1acf-42c8-919a-6394fd1ddfe8")
                        });
                });

            modelBuilder.Entity("JobJournal.Shared.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApplicationMethod")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobApplication");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58e55e99-cbad-4c93-b804-fe8c265f9835"),
                            ApplicationDate = new DateTime(2020, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApplicationMethod = 3,
                            ApplicationStatus = 1,
                            CompanyId = new Guid("ad94a572-5104-4303-82f7-fac0a7d06897"),
                            JobTitle = "CEO",
                            UserId = new Guid("9b27e7b5-1acf-42c8-919a-6394fd1ddfe8")
                        });
                });

            modelBuilder.Entity("JobJournal.Shared.CompanyContact", b =>
                {
                    b.HasOne("JobJournal.Shared.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobJournal.Shared.JobApplication", b =>
                {
                    b.HasOne("JobJournal.Shared.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
